### ISSUE TITLE
isWXAppInstalled always returns false

### ISSUE THREAD

**Issue by kinhunt** [weflex/react-native-wechat#5]
I installed the module, added the url scheme to xcode's info url types. 

```
  WeChat.registerApp("wx81bfaa7ead2e5f7d", function (resultOne) {
            console.log(resultOne)
            WeChat.isWXAppInstalled(function (resultTwo) {
                console.log(resultTwo)
            })
        })
```

resultOne is null, resultTwo is false.

iPhone 6, WeChat 6.3.6, RN 0.14.2, RN-wechat 1.1.1

Any other configuration is required?

**Comment by yorkie** [comment]
Nope, but this seems to be a bug from WeChat iOS SDK, let me reproduce this later, thanks for your report.

**Comment by kinhunt** [comment]
@yorkie  is this fixed in 1.1.2 ?

**Comment by yorkie** [comment]
Sorry, I'm still not able to have enough time to take this issue. Perhaps I will take a look this night :-)

**Comment by kinhunt** [comment]
fixed. 

for iOS9, put these in info.plist

```
<key>LSApplicationQueriesSchemes</key>
  <array>
    <string>weixin</string>
    <string>wechat</string>
  </array>
```
